### ISSUE TITLE
Add event for "entry" created

### ISSUE THREAD

**Issue by DannyWPWS** [wpwhitesecurity/wsal-wpforms#112]
Suggested here https://secure.helpscout.net/conversation/1778960123/5882?folderId=4248868

We dont currently have an event for when a form is submitted (though we do for Gforms) - if we can, lets add one here too!

**Comment by DannyWPWS** [comment]
![image](https://user-images.githubusercontent.com/59394454/154336737-2e838cf2-74be-490b-8946-a53cec442bbd.png)

Iv kept this as a seperate event to 5504 (entry deleted) - as there is as strong chance an admin would want to turn off this event but keep 5504 going I think

**Comment by robert81** [comment]
Event ID 5523 should be the same as we have in GravityForms.

By default should be 5523: User submitted form.
And then have an option underneath it to also capture website visitors.
