### ISSUE TITLE
Notification which advertises the extension is duplicated

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-wpforms#161]
If we remove the WP Forms + WSAL extension, it will cause the advertisement to be duplicated. 

I've tested and this is the only extension for which this happens.

To reproduce:
1. install WP Forms
2. install WSAL + WP Forms extension latest build
3. remove extension.
4. go do the site Dashboard and see the notifications

![w](https://user-images.githubusercontent.com/92275653/226557506-8264e1b5-c57f-4807-8b84-a54f6e11a502.png)

**Comment by sdobreff** [comment]
Unable to reproduce
Tried with the plugin, without it, just deactivating, added table press as its on your screenshot, single install as well as multi install
